const express = require('express')
const bodyParser = require('body-parser')
const rootRoute = require('./routes/rootRoute')
const getBookstores = require('./routes/bookstores/getBookstores')
const addBookstores = require('./routes/bookstores/addBookstores')
const getBooks = require('./routes/books/getBooks')
const addBooks = require('./routes/books/addBooks')
const getInventories = require('./routes/inventories/getInventories')
const addInventories = require('./routes/inventories/addInventories')
const getTypes = require('./routes/types/getTypes')
const addTypes = require('./routes/types/addTypes')
const getGenres = require('./routes/genres/getGenres')
const addGenres = require('./routes/genres/addGenres')
const getAuthors = require('./routes/authors/getAuthors')
const addAuthors = require('./routes/authors/addAuthors')
const getPublishers = require('./routes/publishers/getPublishers')
const addPublishers = require('./routes/publishers/addPublishers')

const app = express()
app.use(bodyParser.json())

app.use(rootRoute)
app.use(getBookstores)
app.use(addBookstores)
app.use(getBooks)
app.use(addBooks)
app.use(getInventories)
app.use(addInventories)
app.use(getTypes)
app.use(addTypes)
app.use(getGenres)
app.use(addGenres)
app.use(getAuthors)
app.use(addAuthors)
app.use(getPublishers)
app.use(addPublishers)

const port = 3000
app.listen(port, () => {
        console.log(`Backend app is running in http://localhost:${port}`);
})